/**
 * EasyTravelApi
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Allocation', 'model/Amount', 'model/AvailableActivity', 'model/AvailableHotel', 'model/AvailableTransfer', 'model/BoardPrice', 'model/BookActivityRQ', 'model/BookActivityRS', 'model/BookHotelRQ', 'model/BookHotelRS', 'model/BookTransferRQ', 'model/BookTransferRS', 'model/Booking', 'model/CancelBookingRS', 'model/CancellationCost', 'model/City', 'model/ConfirmServicesRQ', 'model/ConfirmServicesRS', 'model/Country', 'model/GetActivityPriceDetailsRS', 'model/GetAvailableActivitiesRS', 'model/GetAvailableHotelsRS', 'model/GetAvailableTransfersRS', 'model/GetBookingsRS', 'model/GetDataSheetRS', 'model/GetGrantedHotelsRS', 'model/GetHotelPriceDetailsRS', 'model/GetPortfolioRS', 'model/GetRoomingListRS', 'model/GetTransferPriceDetailsRS', 'model/GrantedHotel', 'model/HolderForAnActivityDate', 'model/HotelBooking', 'model/Option', 'model/Pair', 'model/Remark', 'model/Resource', 'model/RoomId', 'model/ServiceConfirmation', 'model/State', 'model/Stay', 'model/UpdateOperation', 'model/UpdateRQ', 'model/UpdateRS', 'api/DefaultApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Allocation'), require('./model/Amount'), require('./model/AvailableActivity'), require('./model/AvailableHotel'), require('./model/AvailableTransfer'), require('./model/BoardPrice'), require('./model/BookActivityRQ'), require('./model/BookActivityRS'), require('./model/BookHotelRQ'), require('./model/BookHotelRS'), require('./model/BookTransferRQ'), require('./model/BookTransferRS'), require('./model/Booking'), require('./model/CancelBookingRS'), require('./model/CancellationCost'), require('./model/City'), require('./model/ConfirmServicesRQ'), require('./model/ConfirmServicesRS'), require('./model/Country'), require('./model/GetActivityPriceDetailsRS'), require('./model/GetAvailableActivitiesRS'), require('./model/GetAvailableHotelsRS'), require('./model/GetAvailableTransfersRS'), require('./model/GetBookingsRS'), require('./model/GetDataSheetRS'), require('./model/GetGrantedHotelsRS'), require('./model/GetHotelPriceDetailsRS'), require('./model/GetPortfolioRS'), require('./model/GetRoomingListRS'), require('./model/GetTransferPriceDetailsRS'), require('./model/GrantedHotel'), require('./model/HolderForAnActivityDate'), require('./model/HotelBooking'), require('./model/Option'), require('./model/Pair'), require('./model/Remark'), require('./model/Resource'), require('./model/RoomId'), require('./model/ServiceConfirmation'), require('./model/State'), require('./model/Stay'), require('./model/UpdateOperation'), require('./model/UpdateRQ'), require('./model/UpdateRS'), require('./api/DefaultApi'));
  }
}(function(ApiClient, Allocation, Amount, AvailableActivity, AvailableHotel, AvailableTransfer, BoardPrice, BookActivityRQ, BookActivityRS, BookHotelRQ, BookHotelRS, BookTransferRQ, BookTransferRS, Booking, CancelBookingRS, CancellationCost, City, ConfirmServicesRQ, ConfirmServicesRS, Country, GetActivityPriceDetailsRS, GetAvailableActivitiesRS, GetAvailableHotelsRS, GetAvailableTransfersRS, GetBookingsRS, GetDataSheetRS, GetGrantedHotelsRS, GetHotelPriceDetailsRS, GetPortfolioRS, GetRoomingListRS, GetTransferPriceDetailsRS, GrantedHotel, HolderForAnActivityDate, HotelBooking, Option, Pair, Remark, Resource, RoomId, ServiceConfirmation, State, Stay, UpdateOperation, UpdateRQ, UpdateRS, DefaultApi) {
  'use strict';

  /**
   * API_for_travel_agents.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var EasyTravelApi = require('index'); // See note below*.
   * var xxxSvc = new EasyTravelApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new EasyTravelApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new EasyTravelApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new EasyTravelApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.1.9
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Allocation model constructor.
     * @property {module:model/Allocation}
     */
    Allocation: Allocation,
    /**
     * The Amount model constructor.
     * @property {module:model/Amount}
     */
    Amount: Amount,
    /**
     * The AvailableActivity model constructor.
     * @property {module:model/AvailableActivity}
     */
    AvailableActivity: AvailableActivity,
    /**
     * The AvailableHotel model constructor.
     * @property {module:model/AvailableHotel}
     */
    AvailableHotel: AvailableHotel,
    /**
     * The AvailableTransfer model constructor.
     * @property {module:model/AvailableTransfer}
     */
    AvailableTransfer: AvailableTransfer,
    /**
     * The BoardPrice model constructor.
     * @property {module:model/BoardPrice}
     */
    BoardPrice: BoardPrice,
    /**
     * The BookActivityRQ model constructor.
     * @property {module:model/BookActivityRQ}
     */
    BookActivityRQ: BookActivityRQ,
    /**
     * The BookActivityRS model constructor.
     * @property {module:model/BookActivityRS}
     */
    BookActivityRS: BookActivityRS,
    /**
     * The BookHotelRQ model constructor.
     * @property {module:model/BookHotelRQ}
     */
    BookHotelRQ: BookHotelRQ,
    /**
     * The BookHotelRS model constructor.
     * @property {module:model/BookHotelRS}
     */
    BookHotelRS: BookHotelRS,
    /**
     * The BookTransferRQ model constructor.
     * @property {module:model/BookTransferRQ}
     */
    BookTransferRQ: BookTransferRQ,
    /**
     * The BookTransferRS model constructor.
     * @property {module:model/BookTransferRS}
     */
    BookTransferRS: BookTransferRS,
    /**
     * The Booking model constructor.
     * @property {module:model/Booking}
     */
    Booking: Booking,
    /**
     * The CancelBookingRS model constructor.
     * @property {module:model/CancelBookingRS}
     */
    CancelBookingRS: CancelBookingRS,
    /**
     * The CancellationCost model constructor.
     * @property {module:model/CancellationCost}
     */
    CancellationCost: CancellationCost,
    /**
     * The City model constructor.
     * @property {module:model/City}
     */
    City: City,
    /**
     * The ConfirmServicesRQ model constructor.
     * @property {module:model/ConfirmServicesRQ}
     */
    ConfirmServicesRQ: ConfirmServicesRQ,
    /**
     * The ConfirmServicesRS model constructor.
     * @property {module:model/ConfirmServicesRS}
     */
    ConfirmServicesRS: ConfirmServicesRS,
    /**
     * The Country model constructor.
     * @property {module:model/Country}
     */
    Country: Country,
    /**
     * The GetActivityPriceDetailsRS model constructor.
     * @property {module:model/GetActivityPriceDetailsRS}
     */
    GetActivityPriceDetailsRS: GetActivityPriceDetailsRS,
    /**
     * The GetAvailableActivitiesRS model constructor.
     * @property {module:model/GetAvailableActivitiesRS}
     */
    GetAvailableActivitiesRS: GetAvailableActivitiesRS,
    /**
     * The GetAvailableHotelsRS model constructor.
     * @property {module:model/GetAvailableHotelsRS}
     */
    GetAvailableHotelsRS: GetAvailableHotelsRS,
    /**
     * The GetAvailableTransfersRS model constructor.
     * @property {module:model/GetAvailableTransfersRS}
     */
    GetAvailableTransfersRS: GetAvailableTransfersRS,
    /**
     * The GetBookingsRS model constructor.
     * @property {module:model/GetBookingsRS}
     */
    GetBookingsRS: GetBookingsRS,
    /**
     * The GetDataSheetRS model constructor.
     * @property {module:model/GetDataSheetRS}
     */
    GetDataSheetRS: GetDataSheetRS,
    /**
     * The GetGrantedHotelsRS model constructor.
     * @property {module:model/GetGrantedHotelsRS}
     */
    GetGrantedHotelsRS: GetGrantedHotelsRS,
    /**
     * The GetHotelPriceDetailsRS model constructor.
     * @property {module:model/GetHotelPriceDetailsRS}
     */
    GetHotelPriceDetailsRS: GetHotelPriceDetailsRS,
    /**
     * The GetPortfolioRS model constructor.
     * @property {module:model/GetPortfolioRS}
     */
    GetPortfolioRS: GetPortfolioRS,
    /**
     * The GetRoomingListRS model constructor.
     * @property {module:model/GetRoomingListRS}
     */
    GetRoomingListRS: GetRoomingListRS,
    /**
     * The GetTransferPriceDetailsRS model constructor.
     * @property {module:model/GetTransferPriceDetailsRS}
     */
    GetTransferPriceDetailsRS: GetTransferPriceDetailsRS,
    /**
     * The GrantedHotel model constructor.
     * @property {module:model/GrantedHotel}
     */
    GrantedHotel: GrantedHotel,
    /**
     * The HolderForAnActivityDate model constructor.
     * @property {module:model/HolderForAnActivityDate}
     */
    HolderForAnActivityDate: HolderForAnActivityDate,
    /**
     * The HotelBooking model constructor.
     * @property {module:model/HotelBooking}
     */
    HotelBooking: HotelBooking,
    /**
     * The Option model constructor.
     * @property {module:model/Option}
     */
    Option: Option,
    /**
     * The Pair model constructor.
     * @property {module:model/Pair}
     */
    Pair: Pair,
    /**
     * The Remark model constructor.
     * @property {module:model/Remark}
     */
    Remark: Remark,
    /**
     * The Resource model constructor.
     * @property {module:model/Resource}
     */
    Resource: Resource,
    /**
     * The RoomId model constructor.
     * @property {module:model/RoomId}
     */
    RoomId: RoomId,
    /**
     * The ServiceConfirmation model constructor.
     * @property {module:model/ServiceConfirmation}
     */
    ServiceConfirmation: ServiceConfirmation,
    /**
     * The State model constructor.
     * @property {module:model/State}
     */
    State: State,
    /**
     * The Stay model constructor.
     * @property {module:model/Stay}
     */
    Stay: Stay,
    /**
     * The UpdateOperation model constructor.
     * @property {module:model/UpdateOperation}
     */
    UpdateOperation: UpdateOperation,
    /**
     * The UpdateRQ model constructor.
     * @property {module:model/UpdateRQ}
     */
    UpdateRQ: UpdateRQ,
    /**
     * The UpdateRS model constructor.
     * @property {module:model/UpdateRS}
     */
    UpdateRS: UpdateRS,
    /**
     * The DefaultApi service constructor.
     * @property {module:api/DefaultApi}
     */
    DefaultApi: DefaultApi
  };

  return exports;
}));
