/**
 * EasyTravelApi
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Option'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Option'));
  } else {
    // Browser globals (root is window)
    if (!root.EasyTravelApi) {
      root.EasyTravelApi = {};
    }
    root.EasyTravelApi.AvailableHotel = factory(root.EasyTravelApi.ApiClient, root.EasyTravelApi.Option);
  }
}(this, function(ApiClient, Option) {
  'use strict';




  /**
   * The AvailableHotel model module.
   * @module model/AvailableHotel
   * @version 0.1.9
   */

  /**
   * Constructs a new <code>AvailableHotel</code>.
   * An available hotel, including prices
   * @alias module:model/AvailableHotel
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>AvailableHotel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AvailableHotel} obj Optional instance to populate.
   * @return {module:model/AvailableHotel} The populated <code>AvailableHotel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('hotelId')) {
        obj['hotelId'] = ApiClient.convertToType(data['hotelId'], 'String');
      }
      if (data.hasOwnProperty('hotelName')) {
        obj['hotelName'] = ApiClient.convertToType(data['hotelName'], 'String');
      }
      if (data.hasOwnProperty('hotelCategoryId')) {
        obj['hotelCategoryId'] = ApiClient.convertToType(data['hotelCategoryId'], 'String');
      }
      if (data.hasOwnProperty('hotelCategoryName')) {
        obj['hotelCategoryName'] = ApiClient.convertToType(data['hotelCategoryName'], 'String');
      }
      if (data.hasOwnProperty('longitude')) {
        obj['longitude'] = ApiClient.convertToType(data['longitude'], 'String');
      }
      if (data.hasOwnProperty('latitude')) {
        obj['latitude'] = ApiClient.convertToType(data['latitude'], 'String');
      }
      if (data.hasOwnProperty('options')) {
        obj['options'] = ApiClient.convertToType(data['options'], [Option]);
      }
    }
    return obj;
  }

  /**
   * The hotel id
   * @member {String} hotelId
   */
  exports.prototype['hotelId'] = undefined;
  /**
   * The hotel name
   * @member {String} hotelName
   */
  exports.prototype['hotelName'] = undefined;
  /**
   * The hotel category id
   * @member {String} hotelCategoryId
   */
  exports.prototype['hotelCategoryId'] = undefined;
  /**
   * The hotel category name
   * @member {String} hotelCategoryName
   */
  exports.prototype['hotelCategoryName'] = undefined;
  /**
   * Google longitude
   * @member {String} longitude
   */
  exports.prototype['longitude'] = undefined;
  /**
   * Google latitude
   * @member {String} latitude
   */
  exports.prototype['latitude'] = undefined;
  /**
   * List of available options
   * @member {Array.<module:model/Option>} options
   */
  exports.prototype['options'] = undefined;



  return exports;
}));


