/**
 * EasyTravelApi
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EasyTravelApi) {
      root.EasyTravelApi = {};
    }
    root.EasyTravelApi.BookTransferRQ = factory(root.EasyTravelApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BookTransferRQ model module.
   * @module model/BookTransferRQ
   * @version 0.1.9
   */

  /**
   * Constructs a new <code>BookTransferRQ</code>.
   * Container for the transfer service confirmation request
   * @alias module:model/BookTransferRQ
   * @class
   */
  var exports = function() {
    var _this = this;
















  };

  /**
   * Constructs a <code>BookTransferRQ</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BookTransferRQ} obj Optional instance to populate.
   * @return {module:model/BookTransferRQ} The populated <code>BookTransferRQ</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('agentId')) {
        obj['agentId'] = ApiClient.convertToType(data['agentId'], 'String');
      }
      if (data.hasOwnProperty('userName')) {
        obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
      if (data.hasOwnProperty('languageIsoCode')) {
        obj['languageIsoCode'] = ApiClient.convertToType(data['languageIsoCode'], 'String');
      }
      if (data.hasOwnProperty('key')) {
        obj['key'] = ApiClient.convertToType(data['key'], 'String');
      }
      if (data.hasOwnProperty('bookingReference')) {
        obj['bookingReference'] = ApiClient.convertToType(data['bookingReference'], 'String');
      }
      if (data.hasOwnProperty('leadName')) {
        obj['leadName'] = ApiClient.convertToType(data['leadName'], 'String');
      }
      if (data.hasOwnProperty('commentsToProvider')) {
        obj['commentsToProvider'] = ApiClient.convertToType(data['commentsToProvider'], 'String');
      }
      if (data.hasOwnProperty('privateComments')) {
        obj['privateComments'] = ApiClient.convertToType(data['privateComments'], 'String');
      }
      if (data.hasOwnProperty('incomingFlightNumber')) {
        obj['incomingFlightNumber'] = ApiClient.convertToType(data['incomingFlightNumber'], 'String');
      }
      if (data.hasOwnProperty('incomingFlightTime')) {
        obj['incomingFlightTime'] = ApiClient.convertToType(data['incomingFlightTime'], 'Number');
      }
      if (data.hasOwnProperty('incomingFlightOrigin')) {
        obj['incomingFlightOrigin'] = ApiClient.convertToType(data['incomingFlightOrigin'], 'String');
      }
      if (data.hasOwnProperty('outgoingFlightNumber')) {
        obj['outgoingFlightNumber'] = ApiClient.convertToType(data['outgoingFlightNumber'], 'String');
      }
      if (data.hasOwnProperty('outgoingFlightTime')) {
        obj['outgoingFlightTime'] = ApiClient.convertToType(data['outgoingFlightTime'], 'Number');
      }
      if (data.hasOwnProperty('outgoingFlightDestination')) {
        obj['outgoingFlightDestination'] = ApiClient.convertToType(data['outgoingFlightDestination'], 'String');
      }
    }
    return obj;
  }

  /**
   * Your id. As provided
   * @member {String} agentId
   */
  exports.prototype['agentId'] = undefined;
  /**
   * Your user name. As provided
   * @member {String} userName
   */
  exports.prototype['userName'] = undefined;
  /**
   * Your password. As provided
   * @member {String} password
   */
  exports.prototype['password'] = undefined;
  /**
   * The language iso code you want descriptions (when available. E.g. room names, hotel descriptions, ...) to be returned in
   * @member {String} languageIsoCode
   */
  exports.prototype['languageIsoCode'] = undefined;
  /**
   * The price id, as we got it when we asked for available hotels
   * @member {String} key
   */
  exports.prototype['key'] = undefined;
  /**
   * A free text reference you want to appear in the final invoice, so you can match it when validating our invoices
   * @member {String} bookingReference
   */
  exports.prototype['bookingReference'] = undefined;
  /**
   * The lead name
   * @member {String} leadName
   */
  exports.prototype['leadName'] = undefined;
  /**
   * Comments from the customer which should arrive to the activity provider
   * @member {String} commentsToProvider
   */
  exports.prototype['commentsToProvider'] = undefined;
  /**
   * Your comments for us. They will not be visible to the customer neither to the activity provider
   * @member {String} privateComments
   */
  exports.prototype['privateComments'] = undefined;
  /**
   * Incoming flight number
   * @member {String} incomingFlightNumber
   */
  exports.prototype['incomingFlightNumber'] = undefined;
  /**
   * Locale incoming flight time in YYYYMMDDHHMM format
   * @member {Number} incomingFlightTime
   */
  exports.prototype['incomingFlightTime'] = undefined;
  /**
   * Incoming flight origin
   * @member {String} incomingFlightOrigin
   */
  exports.prototype['incomingFlightOrigin'] = undefined;
  /**
   * Outgoing flight number
   * @member {String} outgoingFlightNumber
   */
  exports.prototype['outgoingFlightNumber'] = undefined;
  /**
   * Locale outgoing flight time in YYYYMMDDHHMM format
   * @member {Number} outgoingFlightTime
   */
  exports.prototype['outgoingFlightTime'] = undefined;
  /**
   * Outgoing flight origin
   * @member {String} outgoingFlightDestination
   */
  exports.prototype['outgoingFlightDestination'] = undefined;



  return exports;
}));


