/**
 * EasyTravelApi
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EasyTravelApi) {
      root.EasyTravelApi = {};
    }
    root.EasyTravelApi.BookActivityRQ = factory(root.EasyTravelApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BookActivityRQ model module.
   * @module model/BookActivityRQ
   * @version 0.1.9
   */

  /**
   * Constructs a new <code>BookActivityRQ</code>.
   * Parameters needed to confirm an activity booking
   * @alias module:model/BookActivityRQ
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>BookActivityRQ</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BookActivityRQ} obj Optional instance to populate.
   * @return {module:model/BookActivityRQ} The populated <code>BookActivityRQ</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('key')) {
        obj['key'] = ApiClient.convertToType(data['key'], 'String');
      }
      if (data.hasOwnProperty('leadName')) {
        obj['leadName'] = ApiClient.convertToType(data['leadName'], 'String');
      }
      if (data.hasOwnProperty('commentsToProvider')) {
        obj['commentsToProvider'] = ApiClient.convertToType(data['commentsToProvider'], 'String');
      }
      if (data.hasOwnProperty('privateComments')) {
        obj['privateComments'] = ApiClient.convertToType(data['privateComments'], 'String');
      }
    }
    return obj;
  }

  /**
   * The activity price key, as provided in the /activities/getavailable step
   * @member {String} key
   */
  exports.prototype['key'] = undefined;
  /**
   * The lead name
   * @member {String} leadName
   */
  exports.prototype['leadName'] = undefined;
  /**
   * Comments from the customer which should arrive to the activity provider
   * @member {String} commentsToProvider
   */
  exports.prototype['commentsToProvider'] = undefined;
  /**
   * Your comments for us. They will not be visible to the customer neither to the activity provider
   * @member {String} privateComments
   */
  exports.prototype['privateComments'] = undefined;



  return exports;
}));


