/**
 * EasyTravelApi
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ServiceConfirmation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ServiceConfirmation'));
  } else {
    // Browser globals (root is window)
    if (!root.EasyTravelApi) {
      root.EasyTravelApi = {};
    }
    root.EasyTravelApi.ConfirmServicesRQ = factory(root.EasyTravelApi.ApiClient, root.EasyTravelApi.ServiceConfirmation);
  }
}(this, function(ApiClient, ServiceConfirmation) {
  'use strict';




  /**
   * The ConfirmServicesRQ model module.
   * @module model/ConfirmServicesRQ
   * @version 0.1.9
   */

  /**
   * Constructs a new <code>ConfirmServicesRQ</code>.
   * Container for the confirm services request
   * @alias module:model/ConfirmServicesRQ
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ConfirmServicesRQ</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConfirmServicesRQ} obj Optional instance to populate.
   * @return {module:model/ConfirmServicesRQ} The populated <code>ConfirmServicesRQ</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('serviceConfirmations')) {
        obj['serviceConfirmations'] = ApiClient.convertToType(data['serviceConfirmations'], [ServiceConfirmation]);
      }
    }
    return obj;
  }

  /**
   * List of service confirmations (or rejections)
   * @member {Array.<module:model/ServiceConfirmation>} serviceConfirmations
   */
  exports.prototype['serviceConfirmations'] = undefined;



  return exports;
}));


