/**
 * EasyTravelApi
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EasyTravelApi) {
      root.EasyTravelApi = {};
    }
    root.EasyTravelApi.ServiceConfirmation = factory(root.EasyTravelApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ServiceConfirmation model module.
   * @module model/ServiceConfirmation
   * @version 0.1.9
   */

  /**
   * Constructs a new <code>ServiceConfirmation</code>.
   * Service confirmation data
   * @alias module:model/ServiceConfirmation
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ServiceConfirmation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServiceConfirmation} obj Optional instance to populate.
   * @return {module:model/ServiceConfirmation} The populated <code>ServiceConfirmation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('bookingId')) {
        obj['bookingId'] = ApiClient.convertToType(data['bookingId'], 'String');
      }
      if (data.hasOwnProperty('confirmed')) {
        obj['confirmed'] = ApiClient.convertToType(data['confirmed'], 'Boolean');
      }
      if (data.hasOwnProperty('comments')) {
        obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
      }
    }
    return obj;
  }

  /**
   * Service booking id, as provided by the getroominglist method
   * @member {String} bookingId
   */
  exports.prototype['bookingId'] = undefined;
  /**
   * True if this service is OK. False if this service is not accepted
   * @member {Boolean} confirmed
   * @default false
   */
  exports.prototype['confirmed'] = false;
  /**
   * Comments you want to supply. E.g. the reason to reject the service request
   * @member {String} comments
   */
  exports.prototype['comments'] = undefined;



  return exports;
}));


