/**
 * EasyTravelApi
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/City'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./City'));
  } else {
    // Browser globals (root is window)
    if (!root.EasyTravelApi) {
      root.EasyTravelApi = {};
    }
    root.EasyTravelApi.State = factory(root.EasyTravelApi.ApiClient, root.EasyTravelApi.City);
  }
}(this, function(ApiClient, City) {
  'use strict';




  /**
   * The State model module.
   * @module model/State
   * @version 0.1.9
   */

  /**
   * Constructs a new <code>State</code>.
   * An state inside our portfolio. This is the second level in our product hierarchy
   * @alias module:model/State
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>State</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/State} obj Optional instance to populate.
   * @return {module:model/State} The populated <code>State</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('resourceId')) {
        obj['resourceId'] = ApiClient.convertToType(data['resourceId'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('urlFriendlyName')) {
        obj['urlFriendlyName'] = ApiClient.convertToType(data['urlFriendlyName'], 'String');
      }
      if (data.hasOwnProperty('cities')) {
        obj['cities'] = ApiClient.convertToType(data['cities'], [City]);
      }
    }
    return obj;
  }

  /**
   * This state resource id
   * @member {String} resourceId
   */
  exports.prototype['resourceId'] = undefined;
  /**
   * This state name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The name in a url friendly manner
   * @member {String} urlFriendlyName
   */
  exports.prototype['urlFriendlyName'] = undefined;
  /**
   * List of cities included in this state
   * @member {Array.<module:model/City>} cities
   */
  exports.prototype['cities'] = undefined;



  return exports;
}));


