/**
 * EasyTravelApi
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EasyTravelApi) {
      root.EasyTravelApi = {};
    }
    root.EasyTravelApi.Stay = factory(root.EasyTravelApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Stay model module.
   * @module model/Stay
   * @version 0.1.9
   */

  /**
   * Constructs a new <code>Stay</code>.
   * A stay line inside a hotel booking service
   * @alias module:model/Stay
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>Stay</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Stay} obj Optional instance to populate.
   * @return {module:model/Stay} The populated <code>Stay</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('start')) {
        obj['start'] = ApiClient.convertToType(data['start'], 'Number');
      }
      if (data.hasOwnProperty('end')) {
        obj['end'] = ApiClient.convertToType(data['end'], 'Number');
      }
      if (data.hasOwnProperty('roomId')) {
        obj['roomId'] = ApiClient.convertToType(data['roomId'], 'String');
      }
      if (data.hasOwnProperty('roomName')) {
        obj['roomName'] = ApiClient.convertToType(data['roomName'], 'String');
      }
      if (data.hasOwnProperty('boardBasisId')) {
        obj['boardBasisId'] = ApiClient.convertToType(data['boardBasisId'], 'String');
      }
      if (data.hasOwnProperty('boardBasisName')) {
        obj['boardBasisName'] = ApiClient.convertToType(data['boardBasisName'], 'String');
      }
      if (data.hasOwnProperty('numberOfRooms')) {
        obj['numberOfRooms'] = ApiClient.convertToType(data['numberOfRooms'], 'Number');
      }
      if (data.hasOwnProperty('paxPerRoom')) {
        obj['paxPerRoom'] = ApiClient.convertToType(data['paxPerRoom'], 'Number');
      }
      if (data.hasOwnProperty('ages')) {
        obj['ages'] = ApiClient.convertToType(data['ages'], ['Number']);
      }
    }
    return obj;
  }

  /**
   * When this stay starts in locale. In YYYYMMDD format
   * @member {Number} start
   */
  exports.prototype['start'] = undefined;
  /**
   * When this stay ends in locale. In YYYYMMDD format
   * @member {Number} end
   */
  exports.prototype['end'] = undefined;
  /**
   * The room id
   * @member {String} roomId
   */
  exports.prototype['roomId'] = undefined;
  /**
   * The room name
   * @member {String} roomName
   */
  exports.prototype['roomName'] = undefined;
  /**
   * The board basis id
   * @member {String} boardBasisId
   */
  exports.prototype['boardBasisId'] = undefined;
  /**
   * The board basis name
   * @member {String} boardBasisName
   */
  exports.prototype['boardBasisName'] = undefined;
  /**
   * The number of rooms for this line
   * @member {Number} numberOfRooms
   */
  exports.prototype['numberOfRooms'] = undefined;
  /**
   * How many pax will stay per room for this line
   * @member {Number} paxPerRoom
   */
  exports.prototype['paxPerRoom'] = undefined;
  /**
   * Ages for the pax. If ommited pax will be assumed to be an adult
   * @member {Array.<Number>} ages
   */
  exports.prototype['ages'] = undefined;



  return exports;
}));


