/* 
 * EasyTravelApi
 *
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AvailableHotel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AvailableHotelTests
    {
        // TODO uncomment below to declare an instance variable for AvailableHotel
        //private AvailableHotel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AvailableHotel
            //instance = new AvailableHotel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AvailableHotel
        /// </summary>
        [Test]
        public void AvailableHotelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AvailableHotel
            //Assert.IsInstanceOfType<AvailableHotel> (instance, "variable 'instance' is a AvailableHotel");
        }

        /// <summary>
        /// Test the property 'HotelId'
        /// </summary>
        [Test]
        public void HotelIdTest()
        {
            // TODO unit test for the property 'HotelId'
        }
        /// <summary>
        /// Test the property 'HotelName'
        /// </summary>
        [Test]
        public void HotelNameTest()
        {
            // TODO unit test for the property 'HotelName'
        }
        /// <summary>
        /// Test the property 'HotelCategoryId'
        /// </summary>
        [Test]
        public void HotelCategoryIdTest()
        {
            // TODO unit test for the property 'HotelCategoryId'
        }
        /// <summary>
        /// Test the property 'HotelCategoryName'
        /// </summary>
        [Test]
        public void HotelCategoryNameTest()
        {
            // TODO unit test for the property 'HotelCategoryName'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Test]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }
        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Test]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Test]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }

    }

}
