/* 
 * EasyTravelApi
 *
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BoardPrice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BoardPriceTests
    {
        // TODO uncomment below to declare an instance variable for BoardPrice
        //private BoardPrice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BoardPrice
            //instance = new BoardPrice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BoardPrice
        /// </summary>
        [Test]
        public void BoardPriceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BoardPrice
            //Assert.IsInstanceOfType<BoardPrice> (instance, "variable 'instance' is a BoardPrice");
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'BoardBasisId'
        /// </summary>
        [Test]
        public void BoardBasisIdTest()
        {
            // TODO unit test for the property 'BoardBasisId'
        }
        /// <summary>
        /// Test the property 'BoardBasisName'
        /// </summary>
        [Test]
        public void BoardBasisNameTest()
        {
            // TODO unit test for the property 'BoardBasisName'
        }
        /// <summary>
        /// Test the property 'RetailPrice'
        /// </summary>
        [Test]
        public void RetailPriceTest()
        {
            // TODO unit test for the property 'RetailPrice'
        }
        /// <summary>
        /// Test the property 'NetPrice'
        /// </summary>
        [Test]
        public void NetPriceTest()
        {
            // TODO unit test for the property 'NetPrice'
        }
        /// <summary>
        /// Test the property 'Commission'
        /// </summary>
        [Test]
        public void CommissionTest()
        {
            // TODO unit test for the property 'Commission'
        }
        /// <summary>
        /// Test the property 'Offer'
        /// </summary>
        [Test]
        public void OfferTest()
        {
            // TODO unit test for the property 'Offer'
        }
        /// <summary>
        /// Test the property 'OfferText'
        /// </summary>
        [Test]
        public void OfferTextTest()
        {
            // TODO unit test for the property 'OfferText'
        }
        /// <summary>
        /// Test the property 'OnRequest'
        /// </summary>
        [Test]
        public void OnRequestTest()
        {
            // TODO unit test for the property 'OnRequest'
        }
        /// <summary>
        /// Test the property 'OnRequestText'
        /// </summary>
        [Test]
        public void OnRequestTextTest()
        {
            // TODO unit test for the property 'OnRequestText'
        }
        /// <summary>
        /// Test the property 'NonRefundable'
        /// </summary>
        [Test]
        public void NonRefundableTest()
        {
            // TODO unit test for the property 'NonRefundable'
        }

    }

}
