/* 
 * EasyTravelApi
 *
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BookTransferRQ
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BookTransferRQTests
    {
        // TODO uncomment below to declare an instance variable for BookTransferRQ
        //private BookTransferRQ instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BookTransferRQ
            //instance = new BookTransferRQ();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BookTransferRQ
        /// </summary>
        [Test]
        public void BookTransferRQInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BookTransferRQ
            //Assert.IsInstanceOfType<BookTransferRQ> (instance, "variable 'instance' is a BookTransferRQ");
        }

        /// <summary>
        /// Test the property 'AgentId'
        /// </summary>
        [Test]
        public void AgentIdTest()
        {
            // TODO unit test for the property 'AgentId'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'LanguageIsoCode'
        /// </summary>
        [Test]
        public void LanguageIsoCodeTest()
        {
            // TODO unit test for the property 'LanguageIsoCode'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'BookingReference'
        /// </summary>
        [Test]
        public void BookingReferenceTest()
        {
            // TODO unit test for the property 'BookingReference'
        }
        /// <summary>
        /// Test the property 'LeadName'
        /// </summary>
        [Test]
        public void LeadNameTest()
        {
            // TODO unit test for the property 'LeadName'
        }
        /// <summary>
        /// Test the property 'CommentsToProvider'
        /// </summary>
        [Test]
        public void CommentsToProviderTest()
        {
            // TODO unit test for the property 'CommentsToProvider'
        }
        /// <summary>
        /// Test the property 'PrivateComments'
        /// </summary>
        [Test]
        public void PrivateCommentsTest()
        {
            // TODO unit test for the property 'PrivateComments'
        }
        /// <summary>
        /// Test the property 'IncomingFlightNumber'
        /// </summary>
        [Test]
        public void IncomingFlightNumberTest()
        {
            // TODO unit test for the property 'IncomingFlightNumber'
        }
        /// <summary>
        /// Test the property 'IncomingFlightTime'
        /// </summary>
        [Test]
        public void IncomingFlightTimeTest()
        {
            // TODO unit test for the property 'IncomingFlightTime'
        }
        /// <summary>
        /// Test the property 'IncomingFlightOrigin'
        /// </summary>
        [Test]
        public void IncomingFlightOriginTest()
        {
            // TODO unit test for the property 'IncomingFlightOrigin'
        }
        /// <summary>
        /// Test the property 'OutgoingFlightNumber'
        /// </summary>
        [Test]
        public void OutgoingFlightNumberTest()
        {
            // TODO unit test for the property 'OutgoingFlightNumber'
        }
        /// <summary>
        /// Test the property 'OutgoingFlightTime'
        /// </summary>
        [Test]
        public void OutgoingFlightTimeTest()
        {
            // TODO unit test for the property 'OutgoingFlightTime'
        }
        /// <summary>
        /// Test the property 'OutgoingFlightDestination'
        /// </summary>
        [Test]
        public void OutgoingFlightDestinationTest()
        {
            // TODO unit test for the property 'OutgoingFlightDestination'
        }

    }

}
