/* 
 * EasyTravelApi
 *
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Booking
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BookingTests
    {
        // TODO uncomment below to declare an instance variable for Booking
        //private Booking instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Booking
            //instance = new Booking();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Booking
        /// </summary>
        [Test]
        public void BookingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Booking
            //Assert.IsInstanceOfType<Booking> (instance, "variable 'instance' is a Booking");
        }

        /// <summary>
        /// Test the property 'BookingId'
        /// </summary>
        [Test]
        public void BookingIdTest()
        {
            // TODO unit test for the property 'BookingId'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Test]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }
        /// <summary>
        /// Test the property 'ServiceType'
        /// </summary>
        [Test]
        public void ServiceTypeTest()
        {
            // TODO unit test for the property 'ServiceType'
        }
        /// <summary>
        /// Test the property 'ServiceDescription'
        /// </summary>
        [Test]
        public void ServiceDescriptionTest()
        {
            // TODO unit test for the property 'ServiceDescription'
        }
        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Test]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Test]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'LeadName'
        /// </summary>
        [Test]
        public void LeadNameTest()
        {
            // TODO unit test for the property 'LeadName'
        }
        /// <summary>
        /// Test the property 'RetailValue'
        /// </summary>
        [Test]
        public void RetailValueTest()
        {
            // TODO unit test for the property 'RetailValue'
        }
        /// <summary>
        /// Test the property 'NetValue'
        /// </summary>
        [Test]
        public void NetValueTest()
        {
            // TODO unit test for the property 'NetValue'
        }
        /// <summary>
        /// Test the property 'CommissionValue'
        /// </summary>
        [Test]
        public void CommissionValueTest()
        {
            // TODO unit test for the property 'CommissionValue'
        }
        /// <summary>
        /// Test the property 'CommentsToProvider'
        /// </summary>
        [Test]
        public void CommentsToProviderTest()
        {
            // TODO unit test for the property 'CommentsToProvider'
        }
        /// <summary>
        /// Test the property 'PrivateComments'
        /// </summary>
        [Test]
        public void PrivateCommentsTest()
        {
            // TODO unit test for the property 'PrivateComments'
        }

    }

}
