/* 
 * EasyTravelApi
 *
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BookActivityRQ
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BookActivityRQTests
    {
        // TODO uncomment below to declare an instance variable for BookActivityRQ
        //private BookActivityRQ instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BookActivityRQ
            //instance = new BookActivityRQ();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BookActivityRQ
        /// </summary>
        [Test]
        public void BookActivityRQInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BookActivityRQ
            //Assert.IsInstanceOfType<BookActivityRQ> (instance, "variable 'instance' is a BookActivityRQ");
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'LeadName'
        /// </summary>
        [Test]
        public void LeadNameTest()
        {
            // TODO unit test for the property 'LeadName'
        }
        /// <summary>
        /// Test the property 'CommentsToProvider'
        /// </summary>
        [Test]
        public void CommentsToProviderTest()
        {
            // TODO unit test for the property 'CommentsToProvider'
        }
        /// <summary>
        /// Test the property 'PrivateComments'
        /// </summary>
        [Test]
        public void PrivateCommentsTest()
        {
            // TODO unit test for the property 'PrivateComments'
        }

    }

}
