/* 
 * EasyTravelApi
 *
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetRoomingListRS
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetRoomingListRSTests
    {
        // TODO uncomment below to declare an instance variable for GetRoomingListRS
        //private GetRoomingListRS instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetRoomingListRS
            //instance = new GetRoomingListRS();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetRoomingListRS
        /// </summary>
        [Test]
        public void GetRoomingListRSInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetRoomingListRS
            //Assert.IsInstanceOfType<GetRoomingListRS> (instance, "variable 'instance' is a GetRoomingListRS");
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'Msg'
        /// </summary>
        [Test]
        public void MsgTest()
        {
            // TODO unit test for the property 'Msg'
        }
        /// <summary>
        /// Test the property 'SystemTime'
        /// </summary>
        [Test]
        public void SystemTimeTest()
        {
            // TODO unit test for the property 'SystemTime'
        }
        /// <summary>
        /// Test the property 'Bookings'
        /// </summary>
        [Test]
        public void BookingsTest()
        {
            // TODO unit test for the property 'Bookings'
        }

    }

}
