/* 
 * EasyTravelApi
 *
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Stay
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StayTests
    {
        // TODO uncomment below to declare an instance variable for Stay
        //private Stay instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Stay
            //instance = new Stay();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Stay
        /// </summary>
        [Test]
        public void StayInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Stay
            //Assert.IsInstanceOfType<Stay> (instance, "variable 'instance' is a Stay");
        }

        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Test]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Test]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }
        /// <summary>
        /// Test the property 'RoomId'
        /// </summary>
        [Test]
        public void RoomIdTest()
        {
            // TODO unit test for the property 'RoomId'
        }
        /// <summary>
        /// Test the property 'RoomName'
        /// </summary>
        [Test]
        public void RoomNameTest()
        {
            // TODO unit test for the property 'RoomName'
        }
        /// <summary>
        /// Test the property 'BoardBasisId'
        /// </summary>
        [Test]
        public void BoardBasisIdTest()
        {
            // TODO unit test for the property 'BoardBasisId'
        }
        /// <summary>
        /// Test the property 'BoardBasisName'
        /// </summary>
        [Test]
        public void BoardBasisNameTest()
        {
            // TODO unit test for the property 'BoardBasisName'
        }
        /// <summary>
        /// Test the property 'NumberOfRooms'
        /// </summary>
        [Test]
        public void NumberOfRoomsTest()
        {
            // TODO unit test for the property 'NumberOfRooms'
        }
        /// <summary>
        /// Test the property 'PaxPerRoom'
        /// </summary>
        [Test]
        public void PaxPerRoomTest()
        {
            // TODO unit test for the property 'PaxPerRoom'
        }
        /// <summary>
        /// Test the property 'Ages'
        /// </summary>
        [Test]
        public void AgesTest()
        {
            // TODO unit test for the property 'Ages'
        }

    }

}
