/* 
 * EasyTravelApi
 *
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// An availabe board basis and its price
    /// </summary>
    [DataContract]
    public partial class BoardPrice :  IEquatable<BoardPrice>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BoardPrice" /> class.
        /// </summary>
        /// <param name="Key">Identifier for this room combination and board basis. You will use it in next steps.</param>
        /// <param name="BoardBasisId">Board basis id.</param>
        /// <param name="BoardBasisName">Board basis name.</param>
        /// <param name="RetailPrice">RetailPrice.</param>
        /// <param name="NetPrice">NetPrice.</param>
        /// <param name="Commission">Commission.</param>
        /// <param name="Offer">A flag to state that this price is an offer (default to false).</param>
        /// <param name="OfferText">The offer description, if this is an offer price.</param>
        /// <param name="OnRequest">A flag to state that this price is only available on request (default to false).</param>
        /// <param name="OnRequestText">Describes why this price is on request.</param>
        /// <param name="NonRefundable">A flag to state that this price is not refundable. No cancellation is allowed (default to false).</param>
        public BoardPrice(string Key = null, string BoardBasisId = null, string BoardBasisName = null, Amount RetailPrice = null, Amount NetPrice = null, Amount Commission = null, bool? Offer = null, string OfferText = null, bool? OnRequest = null, string OnRequestText = null, bool? NonRefundable = null)
        {
            this.Key = Key;
            this.BoardBasisId = BoardBasisId;
            this.BoardBasisName = BoardBasisName;
            this.RetailPrice = RetailPrice;
            this.NetPrice = NetPrice;
            this.Commission = Commission;
            // use default value if no "Offer" provided
            if (Offer == null)
            {
                this.Offer = false;
            }
            else
            {
                this.Offer = Offer;
            }
            this.OfferText = OfferText;
            // use default value if no "OnRequest" provided
            if (OnRequest == null)
            {
                this.OnRequest = false;
            }
            else
            {
                this.OnRequest = OnRequest;
            }
            this.OnRequestText = OnRequestText;
            // use default value if no "NonRefundable" provided
            if (NonRefundable == null)
            {
                this.NonRefundable = false;
            }
            else
            {
                this.NonRefundable = NonRefundable;
            }
        }
        
        /// <summary>
        /// Identifier for this room combination and board basis. You will use it in next steps
        /// </summary>
        /// <value>Identifier for this room combination and board basis. You will use it in next steps</value>
        [DataMember(Name="key", EmitDefaultValue=false)]
        public string Key { get; set; }
        /// <summary>
        /// Board basis id
        /// </summary>
        /// <value>Board basis id</value>
        [DataMember(Name="boardBasisId", EmitDefaultValue=false)]
        public string BoardBasisId { get; set; }
        /// <summary>
        /// Board basis name
        /// </summary>
        /// <value>Board basis name</value>
        [DataMember(Name="boardBasisName", EmitDefaultValue=false)]
        public string BoardBasisName { get; set; }
        /// <summary>
        /// Gets or Sets RetailPrice
        /// </summary>
        [DataMember(Name="retailPrice", EmitDefaultValue=false)]
        public Amount RetailPrice { get; set; }
        /// <summary>
        /// Gets or Sets NetPrice
        /// </summary>
        [DataMember(Name="netPrice", EmitDefaultValue=false)]
        public Amount NetPrice { get; set; }
        /// <summary>
        /// Gets or Sets Commission
        /// </summary>
        [DataMember(Name="commission", EmitDefaultValue=false)]
        public Amount Commission { get; set; }
        /// <summary>
        /// A flag to state that this price is an offer
        /// </summary>
        /// <value>A flag to state that this price is an offer</value>
        [DataMember(Name="offer", EmitDefaultValue=false)]
        public bool? Offer { get; set; }
        /// <summary>
        /// The offer description, if this is an offer price
        /// </summary>
        /// <value>The offer description, if this is an offer price</value>
        [DataMember(Name="offerText", EmitDefaultValue=false)]
        public string OfferText { get; set; }
        /// <summary>
        /// A flag to state that this price is only available on request
        /// </summary>
        /// <value>A flag to state that this price is only available on request</value>
        [DataMember(Name="onRequest", EmitDefaultValue=false)]
        public bool? OnRequest { get; set; }
        /// <summary>
        /// Describes why this price is on request
        /// </summary>
        /// <value>Describes why this price is on request</value>
        [DataMember(Name="onRequestText", EmitDefaultValue=false)]
        public string OnRequestText { get; set; }
        /// <summary>
        /// A flag to state that this price is not refundable. No cancellation is allowed
        /// </summary>
        /// <value>A flag to state that this price is not refundable. No cancellation is allowed</value>
        [DataMember(Name="nonRefundable", EmitDefaultValue=false)]
        public bool? NonRefundable { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BoardPrice {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  BoardBasisId: ").Append(BoardBasisId).Append("\n");
            sb.Append("  BoardBasisName: ").Append(BoardBasisName).Append("\n");
            sb.Append("  RetailPrice: ").Append(RetailPrice).Append("\n");
            sb.Append("  NetPrice: ").Append(NetPrice).Append("\n");
            sb.Append("  Commission: ").Append(Commission).Append("\n");
            sb.Append("  Offer: ").Append(Offer).Append("\n");
            sb.Append("  OfferText: ").Append(OfferText).Append("\n");
            sb.Append("  OnRequest: ").Append(OnRequest).Append("\n");
            sb.Append("  OnRequestText: ").Append(OnRequestText).Append("\n");
            sb.Append("  NonRefundable: ").Append(NonRefundable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as BoardPrice);
        }

        /// <summary>
        /// Returns true if BoardPrice instances are equal
        /// </summary>
        /// <param name="other">Instance of BoardPrice to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BoardPrice other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Key == other.Key ||
                    this.Key != null &&
                    this.Key.Equals(other.Key)
                ) && 
                (
                    this.BoardBasisId == other.BoardBasisId ||
                    this.BoardBasisId != null &&
                    this.BoardBasisId.Equals(other.BoardBasisId)
                ) && 
                (
                    this.BoardBasisName == other.BoardBasisName ||
                    this.BoardBasisName != null &&
                    this.BoardBasisName.Equals(other.BoardBasisName)
                ) && 
                (
                    this.RetailPrice == other.RetailPrice ||
                    this.RetailPrice != null &&
                    this.RetailPrice.Equals(other.RetailPrice)
                ) && 
                (
                    this.NetPrice == other.NetPrice ||
                    this.NetPrice != null &&
                    this.NetPrice.Equals(other.NetPrice)
                ) && 
                (
                    this.Commission == other.Commission ||
                    this.Commission != null &&
                    this.Commission.Equals(other.Commission)
                ) && 
                (
                    this.Offer == other.Offer ||
                    this.Offer != null &&
                    this.Offer.Equals(other.Offer)
                ) && 
                (
                    this.OfferText == other.OfferText ||
                    this.OfferText != null &&
                    this.OfferText.Equals(other.OfferText)
                ) && 
                (
                    this.OnRequest == other.OnRequest ||
                    this.OnRequest != null &&
                    this.OnRequest.Equals(other.OnRequest)
                ) && 
                (
                    this.OnRequestText == other.OnRequestText ||
                    this.OnRequestText != null &&
                    this.OnRequestText.Equals(other.OnRequestText)
                ) && 
                (
                    this.NonRefundable == other.NonRefundable ||
                    this.NonRefundable != null &&
                    this.NonRefundable.Equals(other.NonRefundable)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Key != null)
                    hash = hash * 59 + this.Key.GetHashCode();
                if (this.BoardBasisId != null)
                    hash = hash * 59 + this.BoardBasisId.GetHashCode();
                if (this.BoardBasisName != null)
                    hash = hash * 59 + this.BoardBasisName.GetHashCode();
                if (this.RetailPrice != null)
                    hash = hash * 59 + this.RetailPrice.GetHashCode();
                if (this.NetPrice != null)
                    hash = hash * 59 + this.NetPrice.GetHashCode();
                if (this.Commission != null)
                    hash = hash * 59 + this.Commission.GetHashCode();
                if (this.Offer != null)
                    hash = hash * 59 + this.Offer.GetHashCode();
                if (this.OfferText != null)
                    hash = hash * 59 + this.OfferText.GetHashCode();
                if (this.OnRequest != null)
                    hash = hash * 59 + this.OnRequest.GetHashCode();
                if (this.OnRequestText != null)
                    hash = hash * 59 + this.OnRequestText.GetHashCode();
                if (this.NonRefundable != null)
                    hash = hash * 59 + this.NonRefundable.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
