/* 
 * EasyTravelApi
 *
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// CancellationCost
    /// </summary>
    [DataContract]
    public partial class CancellationCost :  IEquatable<CancellationCost>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CancellationCost" /> class.
        /// </summary>
        /// <param name="Retail">Retail.</param>
        /// <param name="Commission">Commission.</param>
        /// <param name="Net">Net.</param>
        /// <param name="Gmttime">Gmttime.</param>
        public CancellationCost(Amount Retail = null, Amount Commission = null, Amount Net = null, string Gmttime = null)
        {
            this.Retail = Retail;
            this.Commission = Commission;
            this.Net = Net;
            this.Gmttime = Gmttime;
        }
        
        /// <summary>
        /// Gets or Sets Retail
        /// </summary>
        [DataMember(Name="retail", EmitDefaultValue=false)]
        public Amount Retail { get; set; }
        /// <summary>
        /// Gets or Sets Commission
        /// </summary>
        [DataMember(Name="commission", EmitDefaultValue=false)]
        public Amount Commission { get; set; }
        /// <summary>
        /// Gets or Sets Net
        /// </summary>
        [DataMember(Name="net", EmitDefaultValue=false)]
        public Amount Net { get; set; }
        /// <summary>
        /// Gets or Sets Gmttime
        /// </summary>
        [DataMember(Name="gmttime", EmitDefaultValue=false)]
        public string Gmttime { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CancellationCost {\n");
            sb.Append("  Retail: ").Append(Retail).Append("\n");
            sb.Append("  Commission: ").Append(Commission).Append("\n");
            sb.Append("  Net: ").Append(Net).Append("\n");
            sb.Append("  Gmttime: ").Append(Gmttime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CancellationCost);
        }

        /// <summary>
        /// Returns true if CancellationCost instances are equal
        /// </summary>
        /// <param name="other">Instance of CancellationCost to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CancellationCost other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Retail == other.Retail ||
                    this.Retail != null &&
                    this.Retail.Equals(other.Retail)
                ) && 
                (
                    this.Commission == other.Commission ||
                    this.Commission != null &&
                    this.Commission.Equals(other.Commission)
                ) && 
                (
                    this.Net == other.Net ||
                    this.Net != null &&
                    this.Net.Equals(other.Net)
                ) && 
                (
                    this.Gmttime == other.Gmttime ||
                    this.Gmttime != null &&
                    this.Gmttime.Equals(other.Gmttime)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Retail != null)
                    hash = hash * 59 + this.Retail.GetHashCode();
                if (this.Commission != null)
                    hash = hash * 59 + this.Commission.GetHashCode();
                if (this.Net != null)
                    hash = hash * 59 + this.Net.GetHashCode();
                if (this.Gmttime != null)
                    hash = hash * 59 + this.Gmttime.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
