/* 
 * EasyTravelApi
 *
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Container for the confirm services request
    /// </summary>
    [DataContract]
    public partial class ConfirmServicesRQ :  IEquatable<ConfirmServicesRQ>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfirmServicesRQ" /> class.
        /// </summary>
        /// <param name="ServiceConfirmations">List of service confirmations (or rejections).</param>
        public ConfirmServicesRQ(List<ServiceConfirmation> ServiceConfirmations = null)
        {
            this.ServiceConfirmations = ServiceConfirmations;
        }
        
        /// <summary>
        /// List of service confirmations (or rejections)
        /// </summary>
        /// <value>List of service confirmations (or rejections)</value>
        [DataMember(Name="serviceConfirmations", EmitDefaultValue=false)]
        public List<ServiceConfirmation> ServiceConfirmations { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConfirmServicesRQ {\n");
            sb.Append("  ServiceConfirmations: ").Append(ServiceConfirmations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ConfirmServicesRQ);
        }

        /// <summary>
        /// Returns true if ConfirmServicesRQ instances are equal
        /// </summary>
        /// <param name="other">Instance of ConfirmServicesRQ to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConfirmServicesRQ other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ServiceConfirmations == other.ServiceConfirmations ||
                    this.ServiceConfirmations != null &&
                    this.ServiceConfirmations.SequenceEqual(other.ServiceConfirmations)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ServiceConfirmations != null)
                    hash = hash * 59 + this.ServiceConfirmations.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
