/**
 * EasyTravelApi
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EasyTravelApi);
  }
}(this, function(expect, EasyTravelApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EasyTravelApi.BookTransferRQ();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BookTransferRQ', function() {
    it('should create an instance of BookTransferRQ', function() {
      // uncomment below and update the code to test BookTransferRQ
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be.a(EasyTravelApi.BookTransferRQ);
    });

    it('should have the property agentId (base name: "agentId")', function() {
      // uncomment below and update the code to test the property agentId
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

    it('should have the property userName (base name: "userName")', function() {
      // uncomment below and update the code to test the property userName
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

    it('should have the property languageIsoCode (base name: "languageIsoCode")', function() {
      // uncomment below and update the code to test the property languageIsoCode
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

    it('should have the property key (base name: "key")', function() {
      // uncomment below and update the code to test the property key
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

    it('should have the property bookingReference (base name: "bookingReference")', function() {
      // uncomment below and update the code to test the property bookingReference
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

    it('should have the property leadName (base name: "leadName")', function() {
      // uncomment below and update the code to test the property leadName
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

    it('should have the property commentsToProvider (base name: "commentsToProvider")', function() {
      // uncomment below and update the code to test the property commentsToProvider
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

    it('should have the property privateComments (base name: "privateComments")', function() {
      // uncomment below and update the code to test the property privateComments
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

    it('should have the property incomingFlightNumber (base name: "incomingFlightNumber")', function() {
      // uncomment below and update the code to test the property incomingFlightNumber
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

    it('should have the property incomingFlightTime (base name: "incomingFlightTime")', function() {
      // uncomment below and update the code to test the property incomingFlightTime
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

    it('should have the property incomingFlightOrigin (base name: "incomingFlightOrigin")', function() {
      // uncomment below and update the code to test the property incomingFlightOrigin
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

    it('should have the property outgoingFlightNumber (base name: "outgoingFlightNumber")', function() {
      // uncomment below and update the code to test the property outgoingFlightNumber
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

    it('should have the property outgoingFlightTime (base name: "outgoingFlightTime")', function() {
      // uncomment below and update the code to test the property outgoingFlightTime
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

    it('should have the property outgoingFlightDestination (base name: "outgoingFlightDestination")', function() {
      // uncomment below and update the code to test the property outgoingFlightDestination
      //var instane = new EasyTravelApi.BookTransferRQ();
      //expect(instance).to.be();
    });

  });

}));
