/**
 * EasyTravelApi
 * API for travel agents
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EasyTravelApi);
  }
}(this, function(expect, EasyTravelApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EasyTravelApi.HotelBooking();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HotelBooking', function() {
    it('should create an instance of HotelBooking', function() {
      // uncomment below and update the code to test HotelBooking
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be.a(EasyTravelApi.HotelBooking);
    });

    it('should have the property bookingId (base name: "bookingId")', function() {
      // uncomment below and update the code to test the property bookingId
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "createdBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property modified (base name: "modified")', function() {
      // uncomment below and update the code to test the property modified
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property serviceType (base name: "serviceType")', function() {
      // uncomment below and update the code to test the property serviceType
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property serviceDescription (base name: "serviceDescription")', function() {
      // uncomment below and update the code to test the property serviceDescription
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property start (base name: "start")', function() {
      // uncomment below and update the code to test the property start
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property end (base name: "end")', function() {
      // uncomment below and update the code to test the property end
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property leadName (base name: "leadName")', function() {
      // uncomment below and update the code to test the property leadName
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property retailValue (base name: "retailValue")', function() {
      // uncomment below and update the code to test the property retailValue
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property netValue (base name: "netValue")', function() {
      // uncomment below and update the code to test the property netValue
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property commissionValue (base name: "commissionValue")', function() {
      // uncomment below and update the code to test the property commissionValue
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property commentsToProvider (base name: "commentsToProvider")', function() {
      // uncomment below and update the code to test the property commentsToProvider
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property privateComments (base name: "privateComments")', function() {
      // uncomment below and update the code to test the property privateComments
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

    it('should have the property stays (base name: "stays")', function() {
      // uncomment below and update the code to test the property stays
      //var instane = new EasyTravelApi.HotelBooking();
      //expect(instance).to.be();
    });

  });

}));
